version: '3.1'

services:
  chat-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB : auth_db
    volumes:
      - chat-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pg
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
volumes:
  chat-data:
networks:
  pg:
    driver: bridge